### ISSUE TITLE
奇怪：开发环境生成的截图就能看到上边框，而线上却看不到

### ISSUE THREAD

**Issue by shuiRong** [thegreatjavascript/FakeScreenshot#2]
本地：
![image](https://user-images.githubusercontent.com/16076993/53403537-d6304c80-39ee-11e9-9e82-d9705cb4eca3.png)

线上：
![image](https://user-images.githubusercontent.com/16076993/53403515-c9135d80-39ee-11e9-8320-e39dc8b9d1ea.png)

**Comment by tuxinghuan** [comment]
fixed
