### ISSUE TITLE
这句话这么明着写在这不太好吧……

### ISSUE THREAD

**Issue by Alan-Liang** [thegreatjavascript/FakeScreenshot#21]
<https://github.com/thegreatjavascript/FakeScreenshot/blob/c3b6aa0174a64f66496c2a428a15a7a66956487f/src/components/sina/simple/data.json#L45>

**Comment by shuiRong** [comment]
的确不太妥当，避免争议[换掉了](https://github.com/thegreatjavascript/FakeScreenshot/pull/22)

**Comment by U2FsdGVkX1** [comment]
https://github.com/thegreatjavascript/FakeScreenshot/commit/488ec370e88cd67b38fae0ccb7f0e44300cce26b
