### ISSUE TITLE
这个现在有人利用污蔑官方媒体制造舆论 建议还是关掉网站吧

### ISSUE THREAD

**Issue by dangzhenghui1985** [thegreatjavascript/FakeScreenshot#23]
https://www.toutiao.com/a6817581214006772231/?tt_from=copy_link&utm_campaign=client_share&timestamp=1587349288&app=news_article&utm_source=copy_link&utm_medium=toutiao_ios&req_id=202004201021280100260790140E9B21FD&group_id=6817581214006772231

**Comment by U2FsdGVkX1** [comment]
工具并没有提供手机版知乎，所以这张图并不是用本工具生成的
另外，即便少了这个工具，污蔑造假也很难停止，而且本工具也生成了水印避免误导，请合理使用

**Comment by shuiRong** [comment]
@dangzhenghui1985 非常感谢你过来提醒。
项目第二个版本已经开发完成，本来打算这两天发布，现在看来得延迟了。好好考虑下怎么打水印才能在「传播与避免被误导」之间达到平衡。

如 @U2FsdGVkX1 所说，那张截图不可能是此工具生成的。任何一个人都可以用PS软件+百度来的PS技巧都可以修改图片上的文字。


> 再说说假截图
> 晚上再补充这块内容

**Comment by WeBeautifulNow** [comment]
而且打开控制台直接修改html也能达到一样的效果把   不是这个软件的锅
