### ISSUE TITLE
【建议】请问能否上架edge商店

### ISSUE THREAD

**Issue by Sev73n** [thegreatjavascript/FakeScreenshot#27]
如图 使用国外商店不方便 请问能否上架edge？ 开发者辛苦了！

**Comment by shuiRong** [comment]
可以啊，我研究下，上架后再回来通知下你。

@Sev73n

**Comment by shuiRong** [comment]
更新：已经提交到 Edge 商店了，现在等待审核通过。
@Sev73n 
![image](https://user-images.githubusercontent.com/16076993/95648406-66120400-0b09-11eb-9fec-ab19772e8d15.png)

**Comment by Sev73n** [comment]
cool 感谢开发者
