### ISSUE TITLE
bug :Safari浏览器中无法下载图片

### ISSUE THREAD

**Issue by tuxinghuan** [thegreatjavascript/FakeScreenshot#3]
问题：Safari浏览器中，下载图片时报错:SecurityError: The operation is insecure.导致无法下载图片

**Comment by tuxinghuan** [comment]
fixed

**Comment by shuiRong** [comment]
[相关commit](https://github.com/thegreatjavascript/FakeScreenshot/commit/970d9f2b66188750262096ac267146d34fe95771)
