### ISSUE TITLE
[Feature Request] 支持企业微信

### ISSUE THREAD

**Issue by LKI** [thegreatjavascript/FakeScreenshot#30]
项目太好用了（

**Comment by shuiRong** [comment]
谢谢。支持不了微信软件。

这个项目的技术原理造成了它只能用在浏览器上，也就是说：目标只能是网页。

**Comment by LKI** [comment]
呃，我想说的是支持的截图类型包括企业微信…（因为我看已经支持了微信的对话支持了

**Comment by shuiRong** [comment]
> 因为我看已经支持了微信的对话支持了

你是说这个App项目吗？ https://github.com/thegreatjavascript/FakeScreenshotApp
