### ISSUE TITLE
@shuiRong shuiRong

### ISSUE THREAD

**Issue by 2631789651** [thegreatjavascript/FakeScreenshot#32]
怎么下载啊，求个大佬交一下   真看不懂   谢谢了

**Comment by shuiRong** [comment]
0. 必须先翻墙，比如能成功访问2中的链接。
1. 下载个Chrome浏览器
2. 用Chrome浏览器打开 https://chrome.google.com/webstore/detail/fakescreenshot/jiojdapfbpmhpihdejiglphhoeakjhmi 
3. 点击右上方的 「添加至Chrome」下载安装。
4. 扩展最后会出现在浏览器的右上方工具栏。
