### ISSUE TITLE
Edge可以安装但被标记为恶意，谷歌浏览器插件商店将其下架

### ISSUE THREAD

**Issue by loveadguard** [thegreatjavascript/FakeScreenshot#36]
@[shuiRong](https://github.com/thegreatjavascript/FakeScreenshot/commits?author=shuiRong)
插件已经彻底无法使用，原本这个插件是兼容Edge浏览器的而且可以安装使用后来被Edge标记为恶意，谷歌浏览器插件商店将其下架，原因可能是这个插件可以修改网页的内容，让骗子有了可乘之机，所以后来就直接下架了

**Comment by shuiRong** [comment]
感谢反馈，其实下架原因不是猜测这样。

只是代码里的一个CSS需要被删除，但之前没有留意Google的邮件，过了期限就给下架了。我调整下代码，就可以申请重新上线了。
