### ISSUE TITLE
谷歌商店搜索不到呀？

### ISSUE THREAD

**Issue by yuanxiaotian123** [thegreatjavascript/FakeScreenshot#41]
![123](https://github.com/thegreatjavascript/FakeScreenshot/assets/145645132/4ca7ae85-e4cd-493f-84c1-a9a366d19e3c)

**Comment by shuiRong** [comment]
不好意思，之前被Google Play下架了后就没有再上线了。

现在需要手动下载安装包下载：下载安装包，手动安装到Chrome本地扩展中（注意打开开发者模式）

**Comment by yuanxiaotian123** [comment]
好的好的，谢谢呀
