### ISSUE TITLE
建议图片带点绿色滤镜

### ISSUE THREAD

**Issue by fishcg** [thegreatjavascript/FakeScreenshot#8]
- 需求：有时候要模拟图片被重复下载转帖多次时画质受损的情况，建议加绿

**Comment by shuiRong** [comment]
好想法，dom2image组件支持设置生成的图片的“画质”参数，也可以加上 😃

**Comment by liruihaod** [comment]
了解。列入todolist

**Comment by U2FsdGVkX1** [comment]
https://github.com/thegreatjavascript/FakeScreenshot/commit/84a6e57adc8815757b5acf60a76860b4eca86a20
